pipelines:
  branches:
    master:
      - step:
          name: Deploy master branch to heroku
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/safecash-csat.git HEAD:master
    dev:
      - step:
          name: Deploy dev branch to heroku
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/safecash-csat-ui-stag.git HEAD:master
